# Generated by Django 3.2.4 on 2021-07-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('book_cover', models.ImageField(null=True, upload_to='')),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
